<a href="https://colab.research.google.com/github/pyh3887/Python-Numpy/blob/master/ex2numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# numpy : ndarray
import numpy as np

#ss = ['tom','james','oscar']
ss = [1,2,3.5]
print(ss, '', type(ss))

ss2 = np.array(ss)
print(ss2,'',type(ss2))

# numpy 배열은 성격이 일치 : 성격이 다르면 상위 타입을 따른다 예 > int에 float 이 껴있다면 float 으로 



[1, 2, 3.5]  <class 'list'>
[1.  2.  3.5]  <class 'numpy.ndarray'>


In [8]:
# 메모리 비교 
li = list(range(1,11))
print(li)
print(id(li[0]), id(li[1]))  # 주소값이 다르다 서로다른 객체를 생성함
print(li * 10) #요소별 곱이 아닌 배열을 10 번돌림 

for i in li:
  print(i * 10 , end = ' ')

print()
numpy_arr = np.array(li)
print(id(numpy_arr[0]), id(numpy_arr[1])) # 주소 값이 같다 하나의 기억장소안에 데이터를 쌓아둠 
print(numpy_arr * 10) # 요소별 곱을 사용한다.  



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
10914496 10914528
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
10 20 30 40 50 60 70 80 90 100 
140673450873288 140673450873288
[ 10  20  30  40  50  60  70  80  90 100]


In [23]:
a = np.array([[1,2,3],[4,5,6]],dtype='float32')
print(type(a),' ',a.dtype,' ',a.shape,' ', a.ndim,' ',a.size)
print(a[0,0], a[0,2])
a[0,0] = 100
print(a[0,0], a[0,2])
print(a[[0]]) # 0 행 1열의 자료  2차원
print(a[0]) # 1차원

<class 'numpy.ndarray'>   float32   (2, 3)   2   6
1.0 3.0
100.0 3.0
[[100.   2.   3.]]
[100.   2.   3.]


In [43]:
c = np.zeros((2,2)) # 2 by 2 배열을 0 으로 채움
print(c)
d = np.ones((2,2))
print(d)
d = np.full((2,2),7)
print(d)
e = np.eye(3) # 단위행렬
print(e)

print()
np.random.seed(0) # 난수의 시작위치를 고정
print(np.random.rand(5)) # 균등분포를 따르는 난수 발생
print(np.random.randn(5)) # 정규분포를 따르는 난수 발생 음수발생
print(np.random.normal(0,1,(2,3))) # 평균은 0 표준편차가 1 인 난수
print(np.random.randint(10, size = 6))  # 10 개중 6 개 정수값
print(np.random.randint(10, size = (3,4))) 
print(np.random.randint(10, size = (3,4,5)))
print()
print(list(range(10)))
print(np.arange(10))
print()
f = {i:np.random.randn() for i in range(5)}
print(f)


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[-0.84272405  1.96992445  1.26611853 -0.50587654  2.54520078]
[[ 1.08081191  0.48431215  0.57914048]
 [-0.18158257  1.41020463 -0.37447169]]
[0 1 9 9 0 4]
[[7 3 2 7]
 [2 0 0 4]
 [5 5 6 8]]
[[[4 1 4 9 8]
  [1 1 7 9 9]
  [3 6 7 2 0]
  [3 5 9 4 4]]

 [[6 4 4 3 4]
  [4 8 4 3 7]
  [5 5 0 1 5]
  [9 3 0 5 0]]

 [[1 2 4 2 0]
  [3 2 0 7 5]
  [9 0 2 7 2]
  [9 2 3 3 2]]]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]

{0: 0.27519831557632024, 1: 1.076121037518773, 2: 0.1921408343855315, 3: 0.8529259575013671, 4: 0.018357182609979702}


In [60]:
# 슬라이싱 -------------------
a = np.array([1,2,3,4,5])
print(a, type(a))
print(a[1:5:2]) #1부터 5 까지 2만큼
print(a[-5:-2]) # -5 부터 -2 까지
print(a[1:], ' ' ,a[:3])
print()
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a, a.shape)
#print(a[:])
print(a[0],a[0][0], a[0, 0],a[[0]])
print()
print(a[1:,0:2]) # 1행부터 출력하되 ,



[1 2 3 4 5] <class 'numpy.ndarray'>
[2 4]
[1 2 3]
[2 3 4 5]   [1 2 3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
[1 2 3 4] 1 1 [[1 2 3 4]]

[[ 5  6]
 [ 9 10]]


In [67]:
b = a 
b[0][0] = 100
print(a)
print(b)
c = np.copy(a) # 원본과 별개의 배열 복사본 
c[0][0] = 200 # 원본은 바뀌지않음 , 새로운 객체가 생김
print(a)
print(c)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[200   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [73]:
d = a[:2, 1:3 ]
print(a[0,1])
print(d)
print(d[0,0])
d[0,0] = 300
print(d)
print(a) # d는 a의 서브 배열, d가 바뀔시 a도 바뀜 


300
[[300   3]
 [  6   7]]
300
[[300   3]
 [  6   7]]
[[100 300   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [79]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
r1 = a[1, :] # a[1,] 1차원
print(r1,r1.shape)
r2 = a[1:2, :] # 2차원
print(r2,r2.shape)

[4 5 6] (3,)
[[4 5 6]] (1, 3)


In [84]:
# 배열의 열에 접근하기
c1 = a[:,1] #2행만 슬라이싱
print(c1,c1.shape)
c2 = a[:, 1:2]  #슬라이싱을 어떻게 하느냐에 따라 다름 
print(c2, c2.shape) 

[2 5 8] (3,)
[[2]
 [5]
 [8]] (3, 1)


In [99]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b = np.array([0,2,0,1])
print(b, b.shape)

print(np.arange(4))
print(a)
print()
print(a[np.arange(4),b]) # 기존 배열의 값을 첨자로 사용 가능 
a[np.arange(4),b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1] (4,)
[0 1 2 3]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [101]:
bool_idx = (a>10)
print(bool_idx)
print(a[bool_idx])
print(a[a>10])

[[ True False False]
 [False False  True]
 [ True False False]
 [False  True  True]]
[11 16 17 21 12]
[11 16 17 21 12]
