<a href="https://colab.research.google.com/github/pyh3887/Python-Numpy/blob/master/ex3np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# 배열 연산

import numpy as np

x = np.array([[1,2],[3,4]])  # 2 * 2 
y = np.arange(5,9).reshape(2,2)   # reshape 모양을 재정의 현재 1차원 → 2차원배열로 바꿈 
y = y.astype(np.float32)
print(x , type(x) , x.dtype) 
print(y, type(y) , y.dtype)
print(x + y)  
print(np.add(x,y)) # numpy 의 배열연산 (+)
print(x - y)  
print(np.subtract(x,y)) # numpy 의 배열 (-)

print(x*y)
print(np.multiply(x,y)) # numpy 의 배열 (*)
print(x/y)
print(np.divide(x,y)) # numpy 의 배열 (/)

print()
big_arr = np.random.rand(1000000) 
print(sum(big_arr)) 
print(np.sum(big_arr)) # numpy 의 연산이 더 빠르다

print()
a = [1,2,3,4]
#print(a * 2) 
b = []
for ai in a:
  b.append(ai * 2)

print(b)

c = np.array(a)
print(c * 2)



[[1 2]
 [3 4]] <class 'numpy.ndarray'> int64
[[5. 6.]
 [7. 8.]] <class 'numpy.ndarray'> float32
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

501104.7913447835
501104.7913447627

[2, 4, 6, 8]
[2 4 6 8]


In [26]:
# 벡터의 내적
v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w))   # 9*11 + 10*12
print(np.dot(v,w)) # numpy 의 내적을 구하고 싶을때 dot function 을 이용 

print(x) # 두개의 벡터가 있을시 , 행의개수와 열의개수가 반드시 일치해아한다. 그렇지 않으면 내적계산을 할수가 없다.

print(x.dot(v))
print(np.dot(x,v))
print()
print(np.dot(x,y))






219
219
[[1 2]
 [3 4]]
[29 67]
[29 67]

[[19. 22.]
 [43. 50.]]


In [35]:
print(x)
print(sum(x))
print(np.sum(x, axis = 0)) # 열기준 연산 1+3 , 2+4
print(np.sum(x, axis = 1)) # 행기준 연산 1+2 , 3+4
print(np.cumsum(x)) #누적합
print(np.cumprod(x)) #누적곱

print()
names = np.array(['tom','james','tom','oscar'])
names2 = np.array(['tom','page','john','oscar'])

print(np.unique(names)) # 중복되지 않는 
print(set(names)) 
print(np.intersect1d(names,names2)) # 교집합 중복 x 
print(np.intersect1d(names,names2,assume_unique=True)) # 교집합 중복 o intersectid는 가능
print(np.union1d(names,names2)) # 합집합 중복 허용x 

a = np.arange(12) 
b = a.reshape(3,4)



[[1 2]
 [3 4]]
[4 6]
[4 6]
[3 7]
[ 1  3  6 10]
[ 1  2  6 24]

['james' 'oscar' 'tom']
{'oscar', 'tom', 'james'}
['oscar' 'tom']
['oscar' 'tom' 'tom']
['james' 'john' 'oscar' 'page' 'tom']


In [39]:
# transpose(전치: 행열의 위치 변경)
print(x)
print(x.T)
print(x.transpose())
print(x.swapaxes(0,1))

arr = np.arange(1,16).reshape(3,5) # 3행 5열 2차원배열
print(arr, arr.shape)
print()
print(arr.T) # 행열의 위치를 바꿨음으로 내적을 구할수 있다.
print(arr.flatten()) # 2차원 배열을 다시 1차원 배열로 바꿈


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] (3, 5)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
