<a href="https://colab.research.google.com/github/pyh3887/Python-Numpy/blob/master/ex4np_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

x = np.arange(1,10).reshape(3,3) # 3x3 배열
y = np.array([1,0,1]) 
z = np.empty_like(x)
print(x)
print(y)
print(z)

# x + y
# 방법1 for 
for i in range(3):
  z[i] = x[i] + y
  print(z)

print()
# 방법2 : tile()

kbs = np.tile(y, (3,1)) # 구조를 맞춰 3x3 배열과 연산이 가능해진다
print(kbs)

z = x + kbs

# 방법3 : numpy 의 broadcasting
mbc = x + y 
print(mbc) 
print(mbc + 100) #알아서 broadcasting 됌 




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 0 1]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 4]
 [4 5 6]
 [7 8 9]]
[[2 2 4]
 [5 5 7]
 [7 8 9]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]

[[1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
[[102 102 104]
 [105 105 107]
 [108 108 110]]


In [20]:
#broadcast 예

v = np.array([1,2,3])
w = np.array([4,5])

print(np.reshape(v,(3,1)) * w) # reshape 으로 v를 3x1 을 만들어준뒤 내적을함
print(np.reshape(w,(2,1)) * v) # reshape 으로 w를 2x1 을 만들어준뒤 내적을함

print()
x = np.array([[1,2,3] , [4,5,6]])
print(x + v)
print()
print(x.T + w)  # x의 행열을 바꾸어 w와 연산 이때 w는 broadcasting
print((x.T +w).T) #연산후 다시 행열 전환


[[ 4  5]
 [ 8 10]
 [12 15]]
[[ 4  8 12]
 [ 5 10 15]]

[[2 4 6]
 [5 7 9]]

[[ 5  9]
 [ 6 10]
 [ 7 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [22]:
# NUMPY FILE i / o
print(x)
np.save('test',x) # test.npy
np.savez('test',x) # test.npz
np.savetxt('test',x) # test
!|s-a|
imsi = np.load('test.npy')
print(imsi)
imsi2 = np.loadtxt('test')
print(imsi)

[[1 2 3]
 [4 5 6]]
/bin/bash: -c: line 0: syntax error near unexpected token `|'
/bin/bash: -c: line 0: `|s-a|'
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
