<a href="https://colab.research.google.com/github/pyh3887/Python-Numpy/blob/master/ex5np_insert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# 배열에 행열 추가 , 삭제

import numpy as np

aa = np.eye(3) # 정방행렬 
print(aa)
bb = np.c_[aa, aa[2]] # 열추가
print();print(bb)
cc = np.r_[aa,[aa[2]]] # 행추가
print();print(cc)

a = np.array([1,2,3])
print();print(a)

print();print(np.c_[a]) # reshape 효과
print();print(a.reshape(3,1))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]

[1 2 3]

[[1]
 [2]
 [3]]

[[1]
 [2]
 [3]]


In [24]:
b = np.append(a, [4,5], axis = 0)
print();print(b)
c = np.insert(a,0,[6,7] , axis = 0) # default : axis = 0
print();print(c)
d = np.delete(a,[1])
d = np.delete(a,[1,2])
print();print(d)



[1 2 3 4 5]

[6 7 1 2 3]

[1]


In [31]:
aa = np.arange(1,10).reshape(3,3)
print(aa)
print();print(np.insert(aa,1,99)) # 1번째에 99 추가 차원이 떨어짐 
print();print(np.insert(aa,1,99,axis=0)) # 행기준 1행에 모두 99를 줌
print();print(np.insert(aa,1,99,axis=1)) # 행기준 1열에 모두 99를 줌

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 1 99  2  3  4  5  6  7  8  9]

[[ 1  2  3]
 [99 99 99]
 [ 4  5  6]
 [ 7  8  9]]

[[ 1 99  2  3]
 [ 4 99  5  6]
 [ 7 99  8  9]]


In [35]:
print(aa)
print(np.delete(aa,1)) # 0행 1열값을 지운뒤 차원을 떨어트림
print();print(np.delete(aa,1,axis=0))
print();print(np.delete(aa,1,axis=1))




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 3 4 5 6 7 8 9]

[[1 2 3]
 [7 8 9]]

[[1 3]
 [4 6]
 [7 9]]
