<a href="https://colab.research.google.com/github/pyh3887/Python-Numpy/blob/master/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

## 연습문제 

aa = np.random.randn(5,4)

#cc = np.random.randint(5, size = (5,4))
#print(cc)

print(np.sum(aa[1,])) # 1행의합
print(np.max(aa[1,])) # 1행 최대값
print(np.sum(aa[2,])) # 2행의합
print(np.max(aa[2,])) # 2행 최댓값
print(np.sum(aa[3,])) # 3행의합 
print(np.max(aa[3,])) # 3행의 최댓값

y = np.arange(1,37).reshape(6,6)

print(y)
print(y[1,:])
print(y[:,2])
print()
#print(y[2,2]) 2,
#print(y[2:5,2:5]) #
print(y[2:5,2:5])
print()

ff = np.zeros((6,4))
dd = np.random.randint(20,100, size = (6,))

print(dd)
print()
for i in range(6):    
  ff[i][0] = dd[i]
  for j in range(1,4): 
    ff[i][j] = dd[i]+ j       

for i in range(4):
  ff[0][i] = 1000
  ff[5][i] = 6000

print(ff)   



print()
random = np.random.randn(4,5)
print(random)
print(np.average(random)) # 평균
print(sum(random)) # 합
print(np.std(random)) # 표준편차
print(np.var(random)) # 분산
print(np.max(random)) # 최대
print(np.min(random)) # 최소
print(np.percentile(random,25)) # 1사분위
print(np.percentile(random,50)) # 2사분위
print(np.percentile(random,75)) # 3사분위
print(np.cumsum(random)) # 요소값누적












-2.747128717017231
0.46560190556049114
-1.3902509608920102
0.2563657751179542
-2.5077046835781496
0.6900151630999838
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[ 7  8  9 10 11 12]
[ 3  9 15 21 27 33]

[[15 16 17]
 [21 22 23]
 [27 28 29]]

[92 73 27 47 92 25]

[[1000. 1000. 1000. 1000.]
 [  73.   74.   75.   76.]
 [  27.   28.   29.   30.]
 [  47.   48.   49.   50.]
 [  92.   93.   94.   95.]
 [6000. 6000. 6000. 6000.]]

[[ 0.23007209 -0.64168014  1.23202193 -0.86465537 -0.41794472]
 [ 2.19408871 -0.60697835 -0.13256381 -0.39577723 -0.93440371]
 [-1.43116872  0.60126718  0.3787546   0.26263656  0.29146889]
 [-0.59973821 -1.31479924  0.65677127  1.45755973 -0.98242196]]
-0.05087452418100642
[ 0.39325387 -1.96219055  2.13498399  0.4597637  -2.04330149]
0.9327217168476375
0.8699698010792044
2.194088710220742
-1.4311687206991721
-0.6974239481293858
-0.26417051652499085
0.4343827449060192
[ 0.23007209 -0.4116