<a href="https://colab.research.google.com/github/pyh3887/Python-Numpy/blob/master/ex6np_sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])

conditionData = np.array([True,False,True])
result = np.where(conditionData,x,y)
print(result)

print()
aa = np.where(x >= 2) # x >= 2 인 값의 index
print(aa) #(array([1,2])) index 가나옴
print(x[aa])
print(np.where(x >= 2, x, x*10)) # x >=2 인 값중 참일시 그냥출력 거짓일시 * 10 [10 2 3]
print()
bb = np.random.randn(4,4)
print(bb)


[1 5 3]

(array([1, 2]),)
[2 3]
[10  2  3]

[[ 0.32358807 -1.39067607  1.55930318  0.59793092]
 [ 0.0440347   1.39329117 -1.09666497  0.6859948 ]
 [ 0.53540399 -0.24001258  0.6565268  -0.72293896]
 [-0.9016355   0.87463676  0.30263632  0.0282056 ]]


In [13]:
#배열 결합
print(x)
print(y)

kbs = np.concatenate([x,y]) # 1차원 배열의 결합
print(kbs)
x1 , x2 = np.split(kbs,2) # 1차원 배열의 분리
print(x1)
print(x2)
print()
a = np.arange(1,17).reshape(4,4)
print(a)
x1 , x2 =np.hsplit(a,2) #2번째 열서부터 분리 
print(x1)
print(x2)
x1, x2 = np.vsplit(a,2) # 2번째 행서부터 분리
print(x1)
print(x2)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [25]:
# 추출(복원,비복원) - sampling
import numpy as np
import random 

li = np.array([1,2,3,4,5,6,7])

#복원 

for _ in range(5):
    print(li[random.randint(0,len(li)- 1)], end = ' ')

print()

#비복원
print(random.sample(list(li),k=5))
print(random.sample(range(1,46),k=6))

print()
print(list(np.random.choice(range(1,46),6)))  #복원
print(list(np.random.choice(range(1,46),6,replace=True))) # 복원
print(list(np.random.choice(range(1,46),6,replace=False))) #비복원

print('가중치(확률)를 부여한 랜덤 추출')
ar = 'air book cat d e f god'
ar = ar.split(' ')
print(ar)
print(np.random.choice(ar,3, p=[0.1,0.1,0.1,0.1,0.1,0.1,0.4])) 















2 1 7 5 6 
[2, 6, 3, 4, 1]
[10, 3, 34, 19, 32, 5]

[10, 30, 41, 22, 36, 24]
[24, 31, 3, 1, 42, 31]
[25, 9, 11, 6, 30, 45]
가중치(확률)를 부여한 랜덤 추출
['air', 'book', 'cat', 'd', 'e', 'f', 'god']
['e' 'cat' 'air']
